name: show-directory

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Клонирование репозитория
      - uses: actions/checkout@v4

      # 2. Установка PHP
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer # Убедимся, что Composer установлен

      # 3. Установка зависимостей
      - name: Install dependencies
        run: make install

      # 4. Запуск линтера
      - name: Run linter
        run: make lint

      # 5. Установка PHPUnit, если он не был установлен через Composer
      - name: Install PHPUnit
        run: composer require --dev phpunit/phpunit

      # 6. Запуск тестов
      - name: Run PHPUnit tests
        run: make test-coverage

      # 7. Публикация покрытия кода
      - name: Run tests & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
          # Добавьте секретный ключ Code Climate в настройки репозитория GitHub Actions
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          # Команда для запуска тестов и генерации покрытия кода
          coverageCommand: make test-coverage
          # Локация файла покрытия кода
          coverageLocations: build/logs/clover.xml:clover
          # Отладка
          debug: true